lookin good

diff --git a/extract-amts b/extract-amts
--- a/extract-amts
+++ b/extract-amts
@@ -1,34 +1,27 @@
 #!/bin/bash
 
-function extractAmt() {
-  if [ $# -ne 1 ]; then
-    echo "Supposed to have one bill filepath input."
-    exit 1
+function extract-amts() {
+  if [ -z "$textUrl" ]; then
+    return
+  else
+    echo -e "\n\nabout to procsess $textFp\n\n"
   fi
-
-  # Variables
-  BILL="$1"
-  NAME=$(basename $1)
-  BDIR=$(readlink -f $(dirname "$1"))
-  pkgDoc=$(find $BDIR/.pkg -name 'pkg-*')
-  DB=$(readlink -f $(dirname $0))/.db
-
-  # Derive the bill's ID for database relationships.
-  _type=$(jq '.billType' $pkgDoc | tr -d '"')
-  _billNumber=$(jq '.billNumber' $pkgDoc | tr -d '"')
-  _congress=$(jq '.congress' $pkgDoc | tr -d '"')
-  name=$_congress$_type$_billNumber
-  billId=$(sqlite3 $DB "select id from bill where name='$name'")
-
   # Extra dollar amounts
-  input=($(grep -ob -E '\$ ?[0-9,\.]+' $1))
+  echo 1
+  input=($(grep -ob -E '\$ ?[0-9,\.]+' "$textFp"))
+  echo 2
   if [ ${#input[*]} -eq 0 ]; then
-    if grep '\$' $1; then
+    echo 3
+    if grep '\$' "$textFp"; then
       printf '\t\e[1,31Dollar signs missed\n'
-      exit
+      exit 1
     fi
+    echo -e '\tno dollars'
     return
   fi
+  echo 4
+  billIdInDb=$(sqlite3 "$DB" "select id from bill where lower(name) = lower(\"$billId\");")
+  echo 5
 
   #prompt="List purposes of these amounts in simple language: "
   insertStatement="
@@ -36,6 +29,7 @@ function extractAmt() {
     INSERT INTO amt (amt, billId, offset) VALUES "
   FIRST=0
   for i in ${input[*]}; do
+    echo 5 and $i
     if [ $FIRST -ne 0 ]; then
       insertStatement+=", "
     fi
@@ -43,7 +37,7 @@ function extractAmt() {
     offset="$(echo $i | awk -F: '{print $1}')"
     amount="$(echo $i | awk -F: '{print $2}' | sed -E 's/([0-9,\.]+),\s*$/\1/g')"
     amount=$(echo $amount | sed -E 's/[$,]//g; s/([0-9\.]+)\.$/\1/')
-    insertStatement+="($amount, $billId, $offset)"
+    insertStatement+="($amount, $billIdInDb, $offset)"
     if [ $? -ne 0 ]; then
       echo error
       exit 1
@@ -56,6 +50,10 @@ function extractAmt() {
   done
 
   sqlite3 $DB "$insertStatement;"
+  if [ $? -ne 0 ]; then
+    echo -e "[extract-amts] Insert error:\n\n\t$insertStatement;\n"
+    exit 1
+  fi
   total=$(sqlite3 $DB "select sum(amt) from amt where billId = '$billId' group by billId")
   printf "\ttotal: \$%'21.2f\n" $total
 }
